spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/boke?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 300000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
  data:
    mongodb:
      uri: mongodb://119.23.221.63:27017/monboke
  redis:
    host: 119.23.221.63
    port: 6379
    timeout: 1200
  rabbitmq:
    host: 119.23.221.63
    port: 5672
    username: root
    password: 123456
server:
  port: 8888
jwt:
  header: Authorization
  secret: NDU0NTY4amhmc3NkeHp6eGNxdzIlMjFAJTIxQCUyM2ZmNQ==
  expiration: 720000000